/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.10.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as category from "../category.js";
import type * as classes from "../classes.js";
import type * as competences from "../competences.js";
import type * as complement from "../complement.js";
import type * as cours from "../cours.js";
import type * as criteria from "../criteria.js";
import type * as evaluation_with_grades from "../evaluation_with_grades.js";
import type * as sequence from "../sequence.js";
import type * as students from "../students.js";
import type * as template from "../template.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  category: typeof category;
  classes: typeof classes;
  competences: typeof competences;
  complement: typeof complement;
  cours: typeof cours;
  criteria: typeof criteria;
  evaluation_with_grades: typeof evaluation_with_grades;
  sequence: typeof sequence;
  students: typeof students;
  template: typeof template;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
