name: 'Run Cypress tests'
on: [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'pnpm'
      - run: pnpm install
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_SECRET: ${{ secrets.CYPRESS_SECRET }}
          CYPRESS_RETRIES: 1

      - uses: actions/upload-artifact@v2

        if: failure()

        with:

          retention-days: 1

          path: |

            cypress/videos
