name: "Smoke Tests"
on: [deployment_status]
env:
  BRANCH_NAME: ${{ github.head_ref }}
  CYPRESS_BASE_URL: "https://classroom.jason-suarez.com/"

jobs:
  test-conditions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running Cypress tests on deployment to main"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "CYPRESS_BASE_URL: $CYPRESS_BASE_URL"
          echo "BRANCH_NAME: $BRANCH_NAME"
          echo "Deployment ref: ${{ github.event.deployment.ref }}"
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set branch name
        id: set_branch
        run: |
          echo "BRANCH_NAME=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV
          echo "Branch name: $BRANCH_NAME"


  e2e-test-on-deployment-status-to-main:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running Cypress tests on deployment to main"
          echo "Branch name: $BRANCH_NAME"
          echo "CYPRESS_BASE_URL: $CYPRESS_BASE_URL"

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "pnpm"
      - run: pnpm install
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_RETRIES: 1
