name: End-to-end tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CYPRESS_BASE_URL: "dev.classroom.jason-suarez.com"

jobs:
  smoke-tests-Dev:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "pnpm"
      - run: pnpm install
      - name: Run Cypress
        uses: cypress-io/github-action@v6
